### ISSUE TITLE
Add option to ninja_syntax.Writer.comment to prevent line breaks

### ISSUE THREAD

**Issue by avallee** [ninja-build/ninja#1041] opened 2015-10-23 20:21 UTC
When outputting some comments I don't want some filenames to get broken onto several lines.

    >>> w = ninja_syntax.Writer(sys.stderr)
    >>> w.comment('Generated by /usr/local/home/avallee/averylong-hyphenated-pathnameindeeddontyouthink/itsveryincredible.py')
    # Generated by /usr/local/home/avallee/averylong-hyphenated-
    # pathnameindeeddontyouthink/itsveryincredible.py

**Comment by NiklasRosenstein** [comment] 2015-12-08 01:27
Oh, I see just now that the problem is only about breaking filenames. And I didn't see there was already a PR merged (why is the issue not closes?). My PR might be irrelevant :)

**Closed** 2015-12-08 01:50 UTC
