### ISSUE TITLE
error: ‘struct stat’ has no member named ‘st_mtimensec’ when built with musl

### ISSUE THREAD

**Issue by necktwi** [ninja-build/ninja#1523] opened 2019-01-25 15:46 UTC
```
aarch64-unknown-linux-musl-g++ -MMD -MT build/disk_interface.o -MF build/disk_interface.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python2.7"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -march=armv8-a+crc -mtune=cortex-a53 -mcpu=cortex-a53 -ftree-vectorize -O2 -pipe -fomit-frame-pointer -Wno-error -march=armv8-a+crc -mtune=cortex-a53 -mcpu=cortex-a53 -ftree-vectorize -O2 -pipe -fomit-frame-pointer -Wno-error -c ./src/disk_interface.cc -o build/disk_interface.o
./src/disk_interface.cc: In member function ‘virtual TimeStamp RealDiskInterface::Stat(const string&, std::__cxx11::string*) const’:
./src/disk_interface.cc:216:51: error: ‘struct stat’ has no member named ‘st_mtimensec’; did you mean ‘st_mtim’?
   return (int64_t)st.st_mtime * 1000000000LL + st.st_mtimensec;
                                                   ^~~~~~~~~~~~
                                                   st_mtim

```

some one at `musl` says :
> **musl** is not going to define a macro to identify the platform.  But however the code should pass `_BSD_SOURCE` if g++ won't implicitly define `_GNU_SOURCE`.
> `ninja` should not test user controlled feature macros.

the `_GNU_SOURCE` of C++ won't go away anytime soon. Can you check for `stat` members any other way without checking user controlled feature macros? Or you advice users to use `clang` instead?

**Comment by jhasse** [comment] 2019-01-25 18:47
duplicate of #1510

**Closed by jhasse** 2019-01-25 18:47 UTC
