### ISSUE TITLE
Add option to force rebuild

### ISSUE THREAD

**Issue by mgaunard** [ninja-build/ninja#317] opened 2012-05-26 16:41 UTC
Ninja lacks an option to force re-building of a particular target, like the make -B option.

I would be willing to implement this if someone could guide me through what needs to be done.

**Comment by axel-h** [comment] 2015-04-27 17:17
what about definig a "always" helper dependency that is used as implicitly dependency then?
```
build always: phony

rule doxygen
  command = doxygen $in

build doxy: doxygen Doxyfile | always
```

This is derived from what I'm found work nicely for building opaque sub projects:
```
rule subProjectBuild
    command = somewhere/whatever/magic.sh
    restart = 1    
build subProject.out: subProjectBuild | always
```

**Comment by edbaunton** [comment] 2016-02-09 22:09
Would you consider this -B feature now? I think it would be useful.

**Comment by tfarina** [comment] 2016-02-11 22:02
@edbaunton what has changed for it to be considered now? Actually I would like to have it too, as at least once I needed to force a rebuild, but I don't remember what was the case tbh.

Maybe it would be better if someone could come with a patch? Then we could see if the code added does not add too much complexity to Ninja.

**Comment by colincross** [comment] 2016-02-18 06:08
One use case for -B is when trying to fix warnings for a target.  The build succeeds, but you still want to rerun all the commands to see the output.

**Comment by vmpn** [comment] 2016-10-29 18:38
One more use case is to allow IDE like Eclipse CDT to scan file dependencies with -B -n -v even without having to do a full build

**Comment by astoeckel** [comment] 2017-08-13 04:50
I'm also in favour of `ninja -B`. I'd often like to rerun the entire build without having to run `clean` first in order to check whether there are any compiler warnings left.

**Comment by mqudsi** [comment] 2018-03-16 06:24
@jhasse that’s fundamentally flawed. Output from previous incremental builds cannot be assumed to be representative of the same output starting from scratch.

**Comment by jhasse** [comment] 2018-03-16 08:38
It is not assumed: It's an *option* to explicitly show them.

In case of compiler warnings the output will be the same though, unless you're missing some header dependencies.

**Comment by nico** [comment] 2018-04-05 13:59
People tell me I should be more decisive about closing out things, so let's close this.

**Closed by nico** 2018-04-05 13:59 UTC
Labels: feature

**Comment by ericniebler** [comment] 2020-04-14 23:44
Closing this without fixing it seemed pretty unpopular. I also miss this feature. Please reconsider?

**Comment by jhasse** [comment] 2020-04-15 07:16
@ericniebler `ninja -t clean <target> && ninja <target>` will rebuild <target>. Ninja tries to stay as small as possible, so we're very wary of new command line flags, especially if they can be achieved in other ways like in this case.

**Comment by mahrud** [comment] 2020-05-27 16:19
> @ericniebler `ninja -t clean <target> && ninja <target>` will rebuild `<target>`. Ninja tries to stay as small as possible, so we're very wary of new command line flags, especially if they can be achieved in other ways like in this case.

This is not equivalent. Say I have a `build` target and `test` target. `test` depends on `build`, naturally. I would like to test multiple times, but currently after the first time ninja says `no work to do`. If I do `ninja -t clean test` and `ninja test`, the result is ninja **rebuilding** the project, which can take a lot longer.

**Comment by jhasse** [comment] 2020-05-27 21:37
I assume by "rebuilding the project" you mean that ninja rebuilds the `build` target in addition to the `test` target? This is equivalent to `make -B` AFAIK.

**Comment by fopor** [comment] 2020-08-05 15:58
I second @jhasse on this, I understand the minimalistic approach, but I also miss this feature.
Any chance this could be reconsidered?

**Comment by jhasse** [comment] 2020-08-06 21:44
Actually I was making a point against reconsidering, since `make -B <target>` *is* equivalent to `ninja -t clean <target> && ninja <target>`. Am I missing something here?

**Comment by suratovvlad** [comment] 2020-10-07 12:47
I have different use case.
Microsoft likes to update their compilers every two-three weeks. That makes me crazy, because all precompiled headers should be regenerated after the compiler update.
Even ninja tells me, that I need to rebuild precompiled headers.

> ..\..\..\baselibs\src\core\sql\statementhints.cpp: fatal error C1853: 'C:/viadat/projects/develop_cmake/out/build/x64-Release/baselibs/src/core/pch/CMakeFiles/vs_core_pch.dir/./cmake_pch.cxx.pch' precompiled header file is from a different version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)

The problem is that in the project we have several precompiled headers for different libraries.
And cleaning with `ninja -t clean all` doesn't remove any of header.
![image](https://user-images.githubusercontent.com/3812290/95332551-433ae200-08b4-11eb-8c82-23b5fbfaecc3.png)

So, force rebuild is must have at least in case of precompiled headers regeneration.
Maybe I need to use another tricky command for the cleaning them, but only manual deletion of each file actually helps.
Do you know any?

**Comment by jhasse** [comment] 2020-10-07 12:48
> And cleaning with `ninja -t clean all` doesn't remove any of header.

This is the bug.

**Comment by plq** [comment] 2021-03-18 19:44
CMake generates a build.ninja with a target that rebuilds it when any of the cmake files change.

Running clean is obviously not an option. One hack is to touch one of the dependencies and run ``ninja build.ninja``.

Or you could do ``mv build.ninja build.ninja.old; ninja -f build.ninja.old build.ninja && rm build.ninja.old || mv build.ninja.old build.ninja`` but it's even more hacky.

A simple ``ninja -B build.ninja`` would be very useful.

**Comment by jhasse** [comment] 2021-03-18 21:28
Do you want to re-run cmake? `cmake .`

**Comment by plq** [comment] 2021-03-18 23:10
The cmake command under the RERUN_CMAKE rule I have here is more complicated than a simple ``cmake .``. Maybe it's the same thing? I just wouldn't want to do some research to find out. ``touch ../proj/CMakeLists.txt; ninja build.ninja`` is easier. ``ninja -B build.ninja`` would be even easier-er. Just my two kuruş.

**Comment by jhasse** [comment] 2021-03-19 07:06
It's the same thing. Also try: `ninja rebuild_cache`.

**Comment by infinity0** [comment] 2023-08-18 12:40
I'd like to add some extra arguments in favour of re-opening, instead of resorting to manually touching or deleting the intermediate files:

- It saves 10+ seconds of time figuring out what to type, and this can grow to a couple minutes for complicated build systems that are not your own project. Even for your own project, sometimes you forget exactly how you named everything. Over all users over all projects, this is a lot of time.
- For complicated build projects, there can be intermediate temporary build products arranged in a complex dependency tree. You need to figure out what all of these are, delete them, then run ninja again. This defeats the point of a dependency-tracking build system that is supposed to figure things out for you.

In general, arguments along the lines of "but you can do it with <equivalent shell command>" are bad arguments. By the same argument, the whole of ninja is redundant since I can "do it with <equivalent shell comand>". The point of all computing is to save people time.

**Comment by jhasse** [comment] 2023-08-21 08:53
> [...] instead of resorting to manually touching or deleting the intermediate files [...]

You don't have to, use `ninja -t clean <target> && ninja <target>`.

**Comment by infinity0** [comment] 2023-08-23 21:25
This seems to clean all intermediate files that are an input of `<target>` except for source files. If other targets also depend on those files, then a later run of `ninja` will also rebuild those targets. Instead I'd like to clean only inputs of `<target>` that nothing else depends on, to keep the effect of the rebuild localised. Example:

~~~~
y.c -> y.o -> y
           \
            v
x.c -> x.o -> x
~~~~

I'd like "rebuild `x`" to only clean `x.o` and `x`, and not `y.o` - nor `y` later. For example, if I updated the tool that generates `x.o` in a way that I know doesn't affect anything else. It would also be useful for the "test but don't rebuild" scenario that @mahrud mentioned above, or for rebuilding docs if you updated doxygen but not the compiler.

Yes this is not equivalent to `make -B`.

You could put the functionality in another subcommand like `clean-unique`  / `clean-unique-deps-of` and force people to do the shell-command dance, but I also wonder how many people actually want to clean specific targets but *not* rebuild them afterwards?

**Comment by infinity0** [comment] 2023-08-23 21:35
Slightly more complex example:

~~~~
z.c -> z.o -> z
           \
            v
y.c -> y.o -> y
           \
            v
x.c -> x.o -> x
~~~~

"rebuild `x` `y`" would look at the ancestors of `x` or `y` and exclude ancestors of other (top-level) targets i.e. `z`, the result being to clean `y.c`, `y.o`, `x.c`, `x.o`. In general terms you'd only clean ancestors(requested top-level targets) - ancestors(unrequested top-level targets).

**Comment by jhasse** [comment] 2023-08-25 10:16
Can you open a new issue for that functionality?

**Comment by Challanger524** [comment] 2024-05-02 13:40
> Add option to force rebuild #317 Closed
[mgaunard](https://github.com/mgaunard) opened this issue on May 26, 2012 · 38 comments

Goddamn, 12+ years and we still not there 😡

> [nico](https://github.com/nico) commented [on Apr 5, 2018](https://github.com/ninja-build/ninja/issues/317#issuecomment-378945783)
People tell me I should be more decisive about closing out things, so let's close this.

👆 That dude swallowed hole 30+ downvotes for blatantly [closing](https://github.com/ninja-build/ninja/issues/317#issuecomment-378945783) this topic.

If anybody uses `CMake` see my [workaround](https://discourse.cmake.org/t/ability-to-clean-individual-targets/2980/17?u=int_main) for rebuilding the target

**Comment by jhasse** [comment] 2024-05-02 14:45
@Challanger524 As it was explained the functionality is already there: `ninja -t clean <target> && ninja <target>`
Providing a shortcut for that (i.e. `-B`) is a bad idea IMHO, because most of the time [it hides a different problem](https://en.wikipedia.org/wiki/XY_problem), e.g. missing dependencies and shouldn't be encouraged.

For missing functionality see #2318.

Having an option which will reprint the output of every edge (e.g. to fix warnings) is also something that I would be willing to implement. Feel free to create an issue for that.
