### ISSUE TITLE
Unable to decode ascii colors

### ISSUE THREAD

**Issue by luca020400** [ninja-build/ninja#1151] opened 2016-05-04 16:52 UTC
Ninja isn't able to decode ascii colors

EX:
````bash
cat Makefile
all:
	@echo -e "\033[32mGreen\033[0m"
make
Output: Green written in green

cat build.ninja
...
rule rule2
 description = -e \033[32mGreen\033[0m
 command = /bin/sh -c ""
...
Output:
[1/1] -e \033[32mGreen\033[0m
````

Image:
![screenshot from 2016-05-04 18-49-52](https://cloud.githubusercontent.com/assets/3950785/15021830/3358bb86-1229-11e6-97a9-3b8f82347d3f.png)

**Comment by nico** [comment] 2016-05-04 16:58
What does your ninja.sh do? Ninja lets through ANSI codes if it's writing to a terminal, but attempts to strip them otherwise. (Looks like that's failing though.)

Oh, you mean in the `description` string. That's not passed through the shell, so -e doesn't do anything there. If the `command` does `echo -e ...` then that will show up in green. If you want colors in the description, you need to put the final interpreted byte values there; `-e` doesn't do anything there. (But if you do this, then this slightly breaks elision.)

So you can get most of what you want to do working. The bits that don't work are a dupe of #713.

**Closed by nico** 2016-05-04 16:58 UTC

**Comment by luca020400** [comment] 2016-05-04 17:03
ninja.sh is just a ninja wrapper from kati https://github.com/google/kati
````bash
exec ninja -f ./build.ninja "$@" )
````

Anyway I changed to description = echo -e \033[32mGreen\033[0m and it still doesn't work
