### ISSUE TITLE
Fail to detect host tool (glib-mkenums or any other)

### ISSUE THREAD

**Issue by gtristan** [ninja-build/ninja#1288] opened 2017-06-15 11:57 UTC
When trying to build pango (or gstreamer, or anything) with recent meson + ninja, I get the following error immediately when invoking `ninja -C _builddir`:

```
# ninja -C _builddir
ninja: Entering directory `_builddir'
ninja: error: '/usr/bin/glib-mkenums', needed by 'pango/pango-enum-types.h', missing and no known rule to make it
```

This is with a build.ninja file generated by bleeding edge meson from git (at version 0.41.0). And with both stable released ninja from debian testing (1.7.2), or with ninja directly from git.

After speaking with meson developers, and showing them the ninja file which was generated, they told me this is a problem with ninja, so I am report it here.

Below I have pasted the relevant (I think) portion of the build.ninja file:
```
build pango/pango-enum-types.c: CUSTOM_COMMAND /buildstream/build/_builddir/../pango/pango-enum-types.c.template /buildstream/build/_builddir/../pango/pango.h /buildstream/build/_builddir/../pango/pango-attributes.h /buildstream/build/_builddir/../pango/pango-bidi-type.h /buildstream/build/_builddir/../pango/pango-break.h /buildstream/build/_builddir/../pango/pango-context.h /buildstream/build/_builddir/../pango/pango-coverage.h /buildstream/build/_builddir/../pango/pango-engine.h /buildstream/build/_builddir/../pango/pango-font.h /buildstream/build/_builddir/../pango/pango-fontmap.h /buildstream/build/_builddir/../pango/pango-fontset.h /buildstream/build/_builddir/../pango/pango-glyph.h /buildstream/build/_builddir/../pango/pango-glyph-item.h /buildstream/build/_builddir/../pango/pango-gravity.h /buildstream/build/_builddir/../pango/pango-item.h /buildstream/build/_builddir/../pango/pango-language.h /buildstream/build/_builddir/../pango/pango-layout.h /buildstream/build/_builddir/../pango/pango-matrix.h /buildstream/build/_builddir/../pango/pango-modules.h /buildstream/build/_builddir/../pango/pango-renderer.h /buildstream/build/_builddir/../pango/pango-script.h /buildstream/build/_builddir/../pango/pango-tabs.h /buildstream/build/_builddir/../pango/pango-types.h /buildstream/build/_builddir/../pango/pango-utils.h /buildstream/build/_builddir/../pango/pango-version-macros.h | pango/pango-enum-types.h /usr/bin/glib-mkenums
 COMMAND = /usr/bin/python3 /usr/local/bin/meson --internal exe /buildstream/build/_builddir/meson-private/meson_exe_glib-mkenums_3d7441116f2da222c2b279aa50124bc5e89dda9a.dat
 description = Generating$ pango-enum-types.c$ with$ a$ meson_exe.py$ custom$ command.
```

And attached below is the full build.ninja file generated by meson:
[build.ninja.txt](https://github.com/ninja-build/ninja/files/1077507/build.ninja.txt)

**Comment by gtristan** [comment] 2017-06-15 12:52
Some additional information:

First, I have tried every git tag of ninja down to v1.3.2, same problem occurs, this leads me to suspect it may have something to do with the environment, which is a linux user namespace (done with setuid bubblewrap with some bindmounts). However most everything else is working fine in this environment so I doubt this is the problem.

Also, when running `ninja -C _builddir` under strace, I get some interesting feedback:

```
...
stat("/usr/bin/glib-mkenums", {st_mode=S_IFREG|0755, st_size=19434, ...}) = 0
...
write(2, "ninja: error: ", 14)          = 14
write(2, "'/usr/bin/glib-mkenums', needed "..., 99) = 99
write(2, "\n", 1)                       = 1
```

Hmmm, looks a bit contradictory, attaching full strace log here too
[strace.txt](https://github.com/ninja-build/ninja/files/1077645/strace.txt)

**Comment by gtristan** [comment] 2017-06-15 14:50
Hunting a bit further...

This better strace log with full stat bufs says:
```
stat("/usr/bin/glib-mkenums", {st_dev=makedev(0, 40), st_ino=40, st_mode=S_IFREG|0755, st_nlink=5, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=19434, st_atime=2017-06-15T11:05:52+0000.996210575, st_mtime=0, st_ctime=2017-06-15T13:11:57+0000.608727455}) = 0
```

And ninja -d explain says:
```
ninja explain: /usr/bin/glib-mkenums has no in-edge and is missing
ninja explain: /usr/bin/glib-mkenums is dirty
```

Clearly, `/usr/bin/glib-mkenums` exists and has an mtime of 0... I notice in ninja's StatSingleFile wants to look at the file mtime (and TimeStampFromFileTime() wants to fudge that mtime by 400 years or so) and somewhere along the line... graph.cc says the file is "dirty"... is this a good lead ?

Strace full log:
[strace-full.txt](https://github.com/ninja-build/ninja/files/1077987/strace-full.txt)

Explain full log:
[ninja-explain.txt](https://github.com/ninja-build/ninja/files/1077991/ninja-explain.txt)

**Comment by gtristan** [comment] 2017-06-15 14:59
Solved !

This line of code: https://github.com/ninja-build/ninja/blob/master/src/graph.h#L66 cannot be true.

```
  bool exists() const {
    return mtime_ != 0;
  }
```

If the file has an mtime of 0, which `/usr/bin/glib-mkenums` clearly does, while simultaneously existing... this does *not* mean the file does not exist !

**Comment by sgraham** [comment] 2017-06-15 15:05
Good hunting. :) I think this is #1120 .

**Comment by nico** [comment] 2017-06-15 15:52
Yup, sounds like a dupe of #1120. Maybe you want to send a pull request with the change suggested in https://github.com/ninja-build/ninja/issues/1120#issuecomment-207471857 ?

**Closed by nico** 2017-06-15 15:52 UTC

**Comment by gtristan** [comment] 2017-06-15 15:57
@nico: I'll follow the other thread... but in reply...

I think that could be a decent immediate stop-gap fix (which is important, because it's fairly typical for metabuild systems to zero out timestamps in build sandboxes to ensure consistent results, as ostree does on behalf of flatpak-builder), but ultimately it would be better to return something other than an integer from `StatSingleFile()`, so that timestamp and existence can be treated as separate things.

Of course as usual, doing things the correct way is more risky...

**Comment by nico** [comment] 2017-06-15 16:03
I wrote the patch for that once, I have it in a local branch somewhere. It plumbed a bool all over the place, add a member variable (i.e. higher memory use), and the only benefit was that we run into the 2037 year problem 1 second later. So I wouldn't say it's the correct way, just the more complicated way :-)

**Comment by gtristan** [comment] 2017-06-15 17:46
I'm a bit confused, how is it that some extra memory consumption caused you to hit the 2037 year problem faster than normal ?

**Comment by gtristan** [comment] 2017-06-15 17:48
Or, you mean that it took only one more second than without the patch ?

In which case, it's still more correct because you dont treat mtimes with a magic number as non-existent ?
