### ISSUE TITLE
[RFE] Support periodically printing keep-alive message on no output

### ISSUE THREAD

**Issue by mgorny** [ninja-build/ninja#1506] opened 2018-11-29 19:11 UTC
When running very slow & quiet commands, user can see no output for quite a long time. Besides this being confusing, it e.g. causes the NetBSD LLVM buildbots to assume timeout due to no output from the running jobs. This is especially problematic given that `ninja -v` doesn't forward the output from the command until it finishes.

I think it would be helpful if ninja had an option to enable periodic status reports. For example, if no commands finished in the last N minutes, it could print something like '<timestamp> still running: <num/count> <current-job(s)>'.

**Comment by jhasse** [comment] 2018-11-30 12:48
Duplicate of #111.

**Closed by jhasse** 2018-11-30 12:48 UTC
