### ISSUE TITLE
Environment variable controlling max number of jobs

### ISSUE THREAD

**Issue by scheib** [ninja-build/ninja#922] opened 2015-03-02 23:22 UTC
I'd like to propose an environment variable NINJA_JOBS as an alternative to the command line argument -j.

This would allow systems where the default configuration isn't appropriate to have a single setup step to correct for it but simplify all future command line executions. E.g. environments where distributed build tools such as distcc or goma are used.

Happy to code patch if there's agreement.

**Comment by nico** [comment] 2015-03-03 01:18
dupe of #816, related to #797

(if you want this, can't you just `alias pninja=ninja -j $FOO`?)

**Comment by scheib** [comment] 2015-03-03 23:22
A different name for ninja requires all other aliases, cut-n-paste command lines, and manual entry to conform. I'd rather set an environment variable once and not think about it again.

A same name alias mostly works, ```alias ninja=`which ninja` -j 123```, but trips up if a -j is ever entered. This is (almost) my current work around, but the environment variable seems cleaner.

(Ok, my actual work around has some platform detection
```
alias ninja='`ninja-detect-goma`'
alias ninja-detect-goma='if [ -e ~/goma ]; then if [ `uname` == "Darwin" ]; then echo ninja -j 100; else echo ninja -j 1024; fi; else echo ninja; fi'
```
)

**Comment by nico** [comment] 2015-11-12 00:39
Let's close this as dupe of #816, which we think we don't want to do.

**Closed by nico** 2015-11-12 00:39 UTC
