### ISSUE TITLE
Wrong path resolution in Windows

### ISSUE THREAD

**Issue by oribenshir** [ninja-build/ninja#1965] opened 2021-05-04 17:56 UTC
In Windows, Ninja transmutes all paths to lower case before searching for their stats:
https://github.com/ninja-build/ninja/blob/ce700488e01af33bc478bc986e261e306180b993/src/disk_interface.cc#L125

In 2018 Windows introduced a new feature allowing making folder case sensitive for their support in WSL, for reference: https://www.tenforums.com/tutorials/111293-enable-disable-case-sensitive-attribute-folders-windows-10-a.html

 As a result, building projects with Ninja under these directories fails, as files are not found.

**Comment by jhasse** [comment] 2021-05-04 22:27
Duplicate of #1882.

**Closed by jhasse** 2021-05-04 22:27 UTC
