### ISSUE TITLE
Completed targets do not persist their states, on Void Linux

### ISSUE THREAD

**Issue by advancedwebdeveloper** [ninja-build/ninja#1902] opened 2021-01-04 09:28 UTC
Hello.

In case if there is an interest in fixing: I found a bug, when working on [Void](https://voidlinux.org/) .

Looks like after some set of task ran by Ninja re-running the same top-level task starts the whole process again, even despite that compiled/linked output is present.

Current version of Ninja is 1.10.2

**Comment by jhasse** [comment] 2021-01-08 16:16
Please debug what's going on using `ninja -d explain`.

**Comment by advancedwebdeveloper** [comment] 2021-01-08 16:36
Here you go:
https://www.reddit.com/r/voidlinux/comments/kq5gx8/ninja_1102_does_not_save_states_of_successfully/
https://drive.google.com/file/d/1w-DNRsMu8DdxMxGg2Gh9YgaPOR82a1UW/view?usp=sharing
https://drive.google.com/file/d/1c75dHlSBIrZ7DdFrDlw2_0Yh9WEletQL/view?usp=sharing
https://drive.google.com/file/d/1DrNNLwui-qSmzWWH2uwx_52f4l_Rf7Cl/view?usp=sharing

**Comment by jhasse** [comment] 2021-01-08 16:47
Looks like a duplicate of #1330 to me.

**Closed by jhasse** 2021-01-08 16:47 UTC
