### ISSUE TITLE
Ninja unnecessarily runs gn just after it was run manually

### ISSUE THREAD

**Issue by ilor** [ninja-build/ninja#1718] opened 2020-01-08 20:11 UTC
Somewhat similar to #1376, I am getting an unnecessary re-run of a ninja generator (gn) right after it was run. It's so far been slightly tricky to confidently reproduce in a minimal repro, but it tends to emerge in incremental rebuilds of Chromium for me.

When this issue happens, what I'm seeing is somewhat similar to #1376. I run gn to regenerate ninja files, then ninja decides it needs to re-run gn again based on a build.ninja timestamp, which appears to be incorrect compared to the filesystem state.

The following is a repro I was able to get in a Chromium build, which while far from "minimal" is at least something. I used a recent master ninja version but the issue is not new.
```
$ gn gen out --args="target_os=\"android\""
Done. Made 22794 targets from 1916 files in 5538ms
$ stat -c "%Y %n" out/build.ninja out/args.gn
1578329248 out/build.ninja
1578329243 out/args.gn
$ ninja -C out -d explain
ninja: Entering directory `out'
ninja explain: recorded mtime of build.ninja older than most recent input args.gn (1578329238290052140 vs 1578329243458020060)
[1/1] Regenerating ninja files
```
The mtime of build.ninja on disk is not older than args.gn.

Note however this was not the _first_ build in the `out` directory I did, I had to play with it a bit to enter the broken state. I'll try to figure out if I can get this to happen reliably.

**Comment by ilor** [comment] 2020-01-08 20:32
Looks like the issue starts appearing in a clean build dir when the following happen:
* Some `--args` are passed to `gn gen` (didn't repro without `--args`, args used didn't seem to matter)
* A change to some BUILD.gn file triggered a (correct) gn re-run by ninja
Ninja will then start causing unnecessary gn re-runs after each time `gn gen` is issued manually in this build dir.

Essentially, in a clean Chromium checkout with a recent ninja, I'm getting:
```
$ rm -rf out2
$ gn gen out2 --args="target_os=\"android\""
Done. Made 22794 targets from 1916 files in 5671ms
$ ninja -C out2  # expecting ninja to NOT re-run gn (OK)
ninja: Entering directory `out2'
[builds]
ninja: build stopped: interrupted by user.
$ touch BUILD.gn 
$ ninja -C out2  # expecting ninja to re-run gn (OK)
ninja: Entering directory `out2'
[1/1] Regenerating ninja files
[builds]
ninja: build stopped: interrupted by user.
$ gn gen out2 --args="target_os=\"android\""
Done. Made 22794 targets from 1916 files in 5848ms
$ ninja -C out2  # expecting ninja to NOT re-run gn (NOK)
ninja: Entering directory `out2'
[1/1] Regenerating ninja files
[builds]
```

The build dir then enters a state where each manual gn run causes ninja to re-issue it with a ` -d explain` about build.ninja vs args.gn like I pasted initially.

**Comment by ilor** [comment] 2020-01-08 20:56
Also filed https://bugs.chromium.org/p/gn/issues/detail?id=136 over at gn

**Comment by jhasse** [comment] 2020-01-08 20:58
Have you tried running restat?

**Comment by ilor** [comment] 2020-01-09 16:50
Restat does not seem to be a reliable solution. While it seems to avoid the gn re-run, it has other problems.

In the "real" build I'm experiencing this in, most of the build becomes invalidated after a restat (even without the manual gn run in the middle). Basically:
```
$ ninja -C Debug
ninja: Entering directory `Debug'
ninja: no work to do.
$ ninja -C Debug -t restat
$ ninja -C Debug -j800 
ninja: Entering directory `Debug'
[1/20227] ACTION //components/discardable_memory/public/mojom:mojom__parser(//build/toolchain/android:android_clang_arm)
...
[2142/2142] STAMP obj/default.stamp
```

Reproducing this behavior in a plain chromium build is somewhat annoying as it requires at least a partially finished build, but I'm getting equivalent behavior.
```
$ ninja -C out3 -j800 content_shell_apk|cat
ninja: Entering directory `out3'
ninja: no work to do.
$ ninja -C out3 -t restat
$ ninja -C out3 -j800 content_shell_apk|cat
ninja: Entering directory `out3'
[1/323] SOLINK ./libc++.cr.so
```

ninja -d explain in that case is not helpful to me; starts with a 
```
ninja: Entering directory `out3'
ninja explain: restat of output libc++.cr.so.TOC older than most recent input obj/buildtools/third_party/libc++/libc++/locale.o (1578586478468862856 vs 1578587134173227762)
```

I'm also finding `restat` somewhat... slow? ~3s on an otherwise idle machine, seems significant in what should be an incremental gn re run and rebuild. It's in some cases nearly as long as the actual gn re-run...

**Comment by jhasse** [comment] 2020-01-12 11:40
This could be a bug in restat then (or an under-specified build manifest). And that's the bug I meant [here](https://github.com/ninja-build/ninja/issues/1376#issuecomment-571170712). We need to try to create a minimal reproducible example.

As for Ninja re-runs GN after it was run manually - that is #1376 and expected: Ninja caches mtimes in .ninja_log (since 1.8 I think?) and therefore won't ask the disk. The fix is for GN to run `ninja -t restat`.

> I'm also finding restat somewhat... slow?

Does running `ninja -t recompact` before restat help?

**Comment by ilor** [comment] 2020-01-12 12:55
In a fresh, empty Chromium build dir just generated by gn, both `restat` and `recompact` take around 2.5s and one doesn't speed up the other. That's roughly half the time it takes to generate the build files in the first place, which seems a bit unfortunate. Does restat have to restat _everything_?

The first explain line mentions a .TOC file, IIRC these are used in Chromium for a link rule that uses `restat` to avoid rebuilding in some cases. Could be relevant, I'll see if I can make a small repro based on that.

**Comment by jhasse** [comment] 2020-01-12 12:58
> In a fresh, empty Chromium build dir just generated by gn, both restat and recompact take around 2.5s and one doesn't speed up the other. That's roughly half the time it takes to generate the build files in the first place, which seems a bit unfortunate.

If I'm not mistaken they should both take 0 seconds since there's no .ninja_log yet.

> Does restat have to restat everything?

No, we could allow a parameter to only restat occurrences of that file.

> Could be relevant, I'll see if I can make a small repro based on that.

Thanks :)

**Comment by jhasse** [comment] 2020-01-16 22:58
I forgot that the restat tool unnecessarily loaded in the build.ninja file - that was probably the reason why it took so long. I've fixed that and also added the option to pass outputs to the tool.

You should now be able to run

```
ninja -t restat build.ninja
```

which only restats the necessary build.ninja entry in .ninja_log and avoids unnecessary re-runs.

I've tested it with a Chromium build: The restat took 0.05s on my machine while it was 0.98s before those two commits (and without passing build.ninja).


It's now gn's job to call this when reconfiguring, thus I will close this issue (feel free to reopen though if the above still doesn't work).

**Closed by jhasse** 2020-01-16 22:58 UTC

**Comment by ilor** [comment] 2020-01-17 14:11
That seems to have helped considerably. restat on build.ninja now looks like the thing I should get gn to do over at the gn issue. Thanks!

Do you want a separate bug for the full restat invalidating some parts of the build? It might not be as relevant if gn/cmake can only restat what they need.

**Comment by jhasse** [comment] 2020-01-17 14:14
Thank you for investigating this :)

> Do you want a separate bug for the full restat invalidating some parts of the build? It might not be as relevant if gn/cmake can only restat what they need.

If you could get a minimal reproducible example, then yes. But it might just be some outputs not being specified correctly?

**Comment by drothlis** [comment] 2021-12-17 15:00
Here's a minimal testcase, if I have understood this issue correctly.

**configure**

```
#!/bin/sh

cat > build.ninja <<'EOF'
rule reconfigure
    command = ./configure
    generator = 1
build build.ninja : reconfigure configure

rule echo
    command = echo $out
build test : echo
EOF
```

Running it the first time is OK:

```
$ ./configure
$ ninja -d explain test
Running scope as unit: run-r0f3e018ae3ba46a985e1b59258d60041.scope
ninja explain: output test doesn't exist
[1/1] echo test
test
Build success after 0:00.00
```

This next step is necessary to reproduce this issue. By making ninja run the reconfigure rule, we get an entry for `build.ninja` into `.ninja_log`:

```
$ touch configure
$ ninja -d explain test
ninja explain: output build.ninja older than most recent input configure (1639752848565676123 vs 1639752907603346209)
[1/1] ./configure
ninja explain: output test doesn't exist
[1/1] echo test
test
Build success after 0:00.01
```

Now if configure changes **and** we run it manually then the next ninja invocation will run reconfigure unnecessarily:

```
$ touch configure
$ ./configure
$ stat --format="%n %y" configure build.ninja
configure 2021-12-17 14:56:30.769785467 +0000
build.ninja 2021-12-17 14:56:31.065794407 +0000
$ ninja -d explain test
ninja explain: recorded mtime of build.ninja older than most recent input configure (1639752978485415964 vs 1639752990769785467)
[1/1] ./configure
ninja explain: output test doesn't exist
[1/1] echo test
test
Build success after 0:00.01
```

You can see from the `stat` output that build.ninja is newer on disk, yet ninja still runs the reconfigure rule.

The workaround is to run `ninja -t restat build.ninja` at the end of `configure`, as per @jhasse's [comment above](#issuecomment-575386483).
