### ISSUE TITLE
Support unlimited number of parallel jobs

### ISSUE THREAD

**Issue by paulmenzel** [ninja-build/ninja#1379] opened 2018-02-06 17:14 UTC
It be great if the following GNU Make behavior for `-j` with no argument would be mirrored.

> If the  -j  option  is given without an argument, make will not limit the number of jobs that can run simultaneously.

**Comment by mathstuf** [comment] 2018-02-19 17:03
This is a duplicate of #1309.

**Comment by nico** [comment] 2018-04-05 14:02
Closing as dupe.

**Closed by nico** 2018-04-05 14:02 UTC
