### ISSUE TITLE
Elapsed time display is incorrect with verbose option

### ISSUE THREAD

**Issue by randomascii** [ninja-build/ninja#1172] opened 2016-07-12 20:49 UTC
When building with "ninja -v" the elapsed time displayed by %es is often (always?) incorrect. It appears that the start time is not initialized in this case. Note the different times for running the same build steps with and without -v:

C:\src\chromium4\src>ninja -v -C out\gn_release_official chrome.exe
ninja: Entering directory `out\gn_release_official'
[0 processes, 1/3 @ 0.0/s : 955990.631s ] C:/src/depot_tools/python276_bin/python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:initialexe/chrome.exe /PDB:initialexe/chrome.exe.pdb @initialexe/chrome.exe.rsp
[0 processes, 2/3 @ 0.0/s : 955990.685s ] C:/src/depot_tools/python276_bin/python.exe gyp-win-tool stamp obj/chrome/reorder_imports.inputdeps.stamp
[0 processes, 3/3 @ 0.0/s : 955990.834s ] C:/src/depot_tools/python276_bin/python.exe ../../build/win/reorder-imports.py -i initialexe -o ../gn_release_official -a x64

>ninja -C out\gn_release_official chrome.exe
ninja: Entering directory `out\gn_release_official'
[0 processes, 3/3 @ 0.0/s : 60.164s ] ACTION //chrome:reorder_imports(//build/toolchain/win:x64)

>set ninja
NINJA_STATUS=[%r processes, %f/%t @ %o/s : %es ]

>ninja --version
1.7.1

**Comment by evmar** [comment] 2016-07-12 20:58
Looks like maybe Stopwatch needs to have Restart() called to start it
https://github.com/ninja-build/ninja/blob/b231274de33a6ebaa5ed284eb233fa360d84ad8f/src/metrics.h#L76
and RateInfo's ctor doesn't call it
https://github.com/ninja-build/ninja/blob/5739c144354c826b57042ad0968680c272a95856/src/build.h#L245
and .Restart() is only called when the build completes.  So it's not clear
to me when this was supposed to be started.

**Comment by randomascii** [comment] 2016-07-12 21:24
BTW, I first noticed/mentioned this a few months (???) ago when there was a release to Chrome of a significant new version of ninja - I can't remember what version it was.

**Comment by nico** [comment] 2016-07-13 02:39
dupe of #1146. fixed on trunk, still need to make a 1.7.2 :-/

**Closed by nico** 2016-07-13 02:39 UTC
