### ISSUE TITLE
Please update release version

### ISSUE THREAD

**Issue by quinor** [ninja-build/ninja#1121] opened 2016-03-25 14:23 UTC
The release is half year old. Would you make a new one? There are quite a few bugs fixed :)

**Comment by nico** [comment] 2016-04-04 21:27
Yes, that's a great idea. Let me post a list of stuff I want to do to the list tomorrow or Wednesday (it's not that much), and then let's try to bundle that up within a week and have a call for testing out middle of next week and hopefully a real release in about two weeks.

**Comment by quinor** [comment] 2016-04-04 21:35
Thank you! I would also suggest making some version scheudle (eg. bundle all bugfixes every 3 months or so) so such situation doesn't happen again.

By the way, big thank you for the great build system assembly. I even prefer writing plain ninja than makefiles ;)

**Comment by ismail** [comment] 2016-04-25 18:17
Friendly ping? :)

**Comment by nico** [comment] 2016-04-25 18:35
I merged the things I wanted to merge two weeks ago and sent out a call for testing last week (https://groups.google.com/forum/#!topic/ninja-build/VupZTWQ_2wA). Unless I hear about problems with current trunk, there will be a release this week.

**Comment by ismail** [comment] 2016-04-25 18:38
I just had a report about ninja memory leak: http://bugzilla.suse.com/show_bug.cgi?id=976858 Will test trunk tomorrow and let you know. Probably not a big deal since looks like no one noticed it before.

**Comment by nico** [comment] 2016-04-25 19:37
That's intentional, ninja doesn't free up memory when it shuts down, it just exits (since that's faster). That means leak tools get confused by it. ninja's memory usage shouldn't become huge as it processes a build since temporary work buffers should all get free'd up, but the memory allocated for the in-memory build graph isn't explicitly deallocated (since that's needed during the entire build, and the OS frees it up at the end of a build). When I do a chrome build, ninja's memory use looks reasonable throughout. That's probably working as intended.

(Looking through the stacks there: `AddEdge` allocation -- expected. `Builder::Builder` -- expected. The build and deps logs could be a bit more careful, but it's O(build graph) memory usage too and intentional.)

**Comment by nico** [comment] 2016-05-02 19:02
1.7.1 is out now.

There has been one bugfix after that already (#1147) and there's some discussion on #999, so there'll probably be a 1.7.2 in the not too-distant future to merge at least the first fix, and possibly a fix for the second.

**Closed by nico** 2016-05-02 19:02 UTC
