### ISSUE TITLE
-k 0 is not documented

### ISSUE THREAD

**Issue by orlp** [ninja-build/ninja#1056] opened 2015-11-22 07:02 UTC
Current documentation is the following:

    -k N     keep going until N jobs fail [default=1]

I suggest this instead:

    -k N     keep going until N jobs fail (0 is unbounded) [default=1]

Although the exact wording doesn't matter, a small documentation of this feature would be nice.

**Comment by tfarina** [comment] 2015-11-22 16:34
To me this does not seem to improve much. What unbounded means? Or, passing zero will result in which behavior?

**Comment by orlp** [comment] 2015-11-22 16:38
I'm not a native speaker, so I'm not sure whether I used the right word.

Unbounded in this context means that `ninja` will not stop after any finite number of jobs fail - only when it can no longer make any progress (all leaves in the build dependency tree have failed or completed).

**Comment by nicolasdespres** [comment] 2015-11-23 11:43
What about "unlimited"?

**Comment by orlp** [comment] 2015-11-23 12:54
@nicolasdespres I fail to see how that is an improvement over unbounded. I feel that if one is going to be unclear then so is the other.

**Comment by jimporter** [comment] 2015-12-12 18:08
As a native English speaker, "unlimited" is a bit clearer (and certainly more natural sounding).

**Comment by nico** [comment] 2016-02-02 23:23
dupe of #1006

**Closed by nico** 2016-02-02 23:23 UTC
