### ISSUE TITLE
Add a `-q` "quiet" option.

### ISSUE THREAD

**Issue by chisophugis** [ninja-build/ninja#480] opened 2013-01-06 03:23 UTC
In some scenarios, it would be really nice to have ninja just print nothing.

For example, I'm strace'ing ninja (and its progeny) to get information about what commands are executed during a build (not just by ninja, but also by processes it creates). The workaround I'm currently using is something ugly like:

`strace -f -e 'abbrev=none' -e 'trace=execve' sh -c 'ninja 2>&1 >/dev/null'`

**Comment by jimon** [comment] 2015-05-07 09:11
+1

**Comment by cdyson37** [comment] 2018-08-24 16:56
The lack of a --quiet option is painful when you consider that ninja merges stdout and stderr (for sensible reasons). If you want to see only the tool output (generally just the errors), you have to do something a bit crazy like set NINJA_STATUS=SILENCE_IS_GOLDEN and then grep -v SILENCE_IS_GOLDEN on the output.

**Comment by moroten** [comment] 2018-11-18 14:05
At work, we use `NINJA_STATUS_SLEEP=2000` in #1501 to throttle the output, but setting it to `NINJA_STATUS_SLEEP=inf` would make the build quiet.

**Comment by jonesmz** [comment] 2020-02-05 08:28
Related to, but not a duplicate of, https://github.com/ninja-build/ninja/issues/420

**Comment by megabyde** [comment] 2020-12-10 20:42
+1

**Closed as completed** 2021-05-08 17:42 UTC
Labels: frontend
