### ISSUE TITLE
[Feature Request] Allow 'ninja -t compdb' accept one target

### ISSUE THREAD

**Issue by lk-chen** [ninja-build/ninja#1544] opened 2019-03-24 16:37 UTC
Currently, compdb iterates all edges. I am proposing an option to accept one target name, and only iterate edges it depends on.

e.g.
ninja -t compdb -a //foo:main cc cxx

New help message will be:
usage: ninja -t compdb [options] [target] [rules]

options:
  -x     expand @rspfile style response file invocations
  -a     accept one target name, and only dump compilation database for this target

**Comment by lk-chen** [comment] 2019-03-24 21:21
CI fails due to gcc 4.8.4 didn't enable c++11, any suggestions?
https://travis-ci.org/ninja-build/ninja/jobs/510697426

**Comment by jhasse** [comment] 2019-03-24 21:29
Ninja isn't using C++11 yet. I would use `std::set` instead of `std::unordered_set` in your code.

**Comment by Yogaht** [comment] 2022-09-19 12:19
@jhasse Hi, is this feature supported now? I think it's very useful expecially in large system.

**Comment by mathstuf** [comment] 2022-09-19 12:56
The issue is still open and the linked PR is not merged…so I'd say "no, not yet".

**Comment by itavero** [comment] 2022-12-01 10:22
I just wanted to add a use case that we have for such a feature: we use CMake (with ninja) and also have some static code analysis tools that work off of a compilation database file.
This worked well initially, as we could tell CMake to simply generate a compilation database containing all sources in the project.

However, now we are taking in more external projects, which still get compiled (doing a lot of bare metal embedded stuff, so we have different compile/linker options depending on the targets, making it difficult to maintain a set of precompiled binaries for all external dependencies/projects).
This also means that they are included in the compilation database, but for our SCA we don't really care about these sources (or have different rules for them).

Currently this means configuring the SCA tools to exclude sources from these external projects.
This however is difficult to maintain and I'd rather explicitly include the targets we want to check.
This is where this feature would come into play. Since the rules in Ninja are generated, basically the only known reference I have is the target name.
If I could pass this to `ninja -t compdb` than I can generate specific compilation databases for the SCA tools.

Is there anything I can do to hopefully help move this request (and the linked PR) forward?

**Comment by jhasse** [comment] 2022-12-01 10:48
> Is there anything I can do to hopefully help move this request (and the linked PR) forward?

Yes: I've left some comments in the PR which weren't addressed. You could create a new PR based on the existing one which addresses those or first add some comments if you think my concern are justified.

**Closed** 2024-11-12 16:25 UTC
Labels: feature
