### ISSUE TITLE
Ninja build issue

### ISSUE THREAD

**Issue by HideakiAtsuyo** [ninja-build/ninja#1929] opened 2021-03-16 03:10 UTC
Corrected a Windows issue with https://github.com/ninja-build/ninja/pull/1928

Then i tried to build ninja with the solution but the result:

https://i.imgur.com/hrOiUWb.png

`libninja-re2c.dir` =>

https://i.imgur.com/Yrq1Dxm.png
+
[libninja-re2c.log](https://github.com/ninja-build/ninja/files/6145809/libninja-re2c.log)
+
I taken the "Binaries" from http://gnuwin32.sourceforge.net/packages/re2c.htm

**Comment by okuoku** [comment] 2021-03-16 09:36
It seems re2c binary you point is too old. Since the repository comes with pre-generated C++ sources, you don't need working `re2c` if you do not change `*.in.cc` files.

In case you really need to modify `*.in.cc`, you can compile re2c:

1. Checkout https://github.com/skvadrik/re2c
2. Open re2c directory with visual studio. If you have installed Visual Studio 2019 with standard setup, it will open the directory as CMake project
3. Build it. `re2c.exe` will be generated under `<re2c checkout>/out/build/x64-Debug/re2c.exe`

Again, `re2c` is only required when building Ninja with modified sources with `/*!re2c` comments such as https://github.com/ninja-build/ninja/blob/ac0fe07d9e924661c6c443f4a9503d4f4308fb20/src/depfile_parser.in.cc#L67 . For `depfile_parser.in.cc` the repository comes with pre processed `depfile_parser.cc`.

**Comment by HideakiAtsuyo** [comment] 2021-03-24 18:34
> It seems re2c binary you point is too old. Since the repository comes with pre-generated C++ sources, you don't need working `re2c` if you do not change `*.in.cc` files.
> 
> In case you really need to modify `*.in.cc`, you can compile re2c:
> 
> 1. Checkout https://github.com/skvadrik/re2c
> 2. Open re2c directory with visual studio. If you have installed Visual Studio 2019 with standard setup, it will open the directory as CMake project
> 3. Build it. `re2c.exe` will be generated under `<re2c checkout>/out/build/x64-Debug/re2c.exe`
> 
> Again, `re2c` is only required when building Ninja with modified sources with `/*!re2c` comments such as
> 
> https://github.com/ninja-build/ninja/blob/ac0fe07d9e924661c6c443f4a9503d4f4308fb20/src/depfile_parser.in.cc#L67
> 
> . For `depfile_parser.in.cc` the repository comes with pre processed `depfile_parser.cc`.

I will check this the 27 and i will send the result here :)

**Comment by HideakiAtsuyo** [comment] 2021-03-25 18:41
The build for re2c is a success but i just tried to build normal Ninja repo i didn't made any change

**Comment by HideakiAtsuyo** [comment] 2021-03-25 18:42
It's only Ninja repo but re2c give some build errors and i can't have the build.ninja without

**Comment by HideakiAtsuyo** [comment] 2021-03-25 18:59
> In case you really need to modify `*.in.cc`, you can compile re2c:

https://i.imgur.com/7oFJXzS.png

**Comment by okuoku** [comment] 2021-03-26 12:40
In regard of `libninja-re2c` files, they will be generated **after** `libninja-re2c` project built so it is expected behaviour that these files cannot be found in the Visual Studio at first. You can build `libninja-re2c` project even if Visual Studio say _"The document cannot be opened"_ if you have working `re2c` and CMake found it properly.

Since CMake caches its findings into `CMakeCache.txt` , you can check that file(generated alongside .sln file) and search for `RE2C` for which `re2c` will be used during build.

>  i just tried to build normal Ninja repo i didn't made any change

Have you tried building Ninja without `re2c` ? Since `CMakeCache.txt` may not be updated automatically, you will have to regenerate solution without `re2c` on the `PATH` , or, undefine `RE2C` CMake variable by:

```
cmake -URE2C .
```

In addition, this Ninja repository can be built with Visual Studio open-folder feature just same as `re2c`.

**Comment by HideakiAtsuyo** [comment] 2021-03-26 13:36
> In regard of `libninja-re2c` files, they will be generated **after** `libninja-re2c` project built so it is expected behaviour that these files cannot be found in the Visual Studio at first. You can build `libninja-re2c` project even if Visual Studio say _"The document cannot be opened"_ if you have working `re2c` and CMake found it properly.
> 
> Since CMake caches its findings into `CMakeCache.txt` , you can check that file(generated alongside .sln file) and search for `RE2C` for which `re2c` will be used during build.
> 
> > i just tried to build normal Ninja repo i didn't made any change
> 
> Have you tried building Ninja without `re2c` ? Since `CMakeCache.txt` may not be updated automatically, you will have to regenerate solution without `re2c` on the `PATH` , or, undefine `RE2C` CMake variable by:
> 
> ```
> cmake -URE2C .
> ```
> 
> In addition, this Ninja repository can be built with Visual Studio open-folder feature just same as `re2c`.

Just have to unload the re2c thing so, 
https://i.imgur.com/xLwCd8c.gif

**Comment by okuoku** [comment] 2021-03-26 14:50
> Just have to unload the re2c thing so,

`libninja-re2c` project is always required, even if you don't do `re2c`. Have you checked `CMakeCache.txt` ? In case you don't do `re2c` during build, `RE2C` should be:

```
//Path to a program.
RE2C:FILEPATH=RE2C-NOTFOUND
```

If you have `re2c` on `PATH` or specified `RE2C` manually during generating .sln with `cmake`, `RE2C` will have some path.

```
//Path to a program.
RE2C:FILEPATH=C:/cygwin64/home/oku/repos/re2c/out/build/x64-Debug/re2c.exe
```

in both cases, `libninja-re2c` will be generated and you need it to build Ninja correctly.

**Comment by HideakiAtsuyo** [comment] 2021-03-26 19:17
Ok so in the build folder i updated the re2c.exe path in the CMakeCache.txt, and i always have the same error when i want to build

**Comment by okuoku** [comment] 2021-03-27 03:55
First, removing `re2c` from build works for you? Delete(move) `re2c.exe`, clean up repository (`git clean`) and regenerate solution file with CMake then check `RE2C:FILEPATH` set as `RE2C:FILEPATH=RE2C-NOTFOUND` then build it. 

In case it doesn't work, your checkout, CMake or Visual Studio do not work properly for you and I think it isn't Ninja issue. I have confirmed current HEAD ( https://github.com/ninja-build/ninja/tree/8cd25aa78c2ff2ca8b3712f8c3630d1a095856d9 ) can be compiled successfully with following combinations:

- Windows 10 20H2 English and Japanese
- CMake `3.19.20122902-MSVC_2` (comes with Visual Studio)
- Visual Studio 2019 v16.9.2 
- x64
- NInja generator and MSBuild generator
- Build in GUI and Visual Studio Command prompt
- (with or without `re2c`)

I recommend CMake generation done in Visual Studio Command prompt(x64 Native Tools Command Prompt)

![image](https://user-images.githubusercontent.com/100813/112709218-b4ba2b80-8efa-11eb-9b4b-58bc80d4c075.png)

In case it does not work still, I have no idea what's next... please paste **entire** generation and build log. (You can copy console output with selecting text and hit "Enter"). Since IDE do not provide full logs, build needs to be done with `cmake --build .` 

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.9.2
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>cd c:\build\ninja

c:\build\ninja>cmake c:\cygwin64\home\oku\repos\ninja
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- IPO / LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: C:/build/ninja

c:\build\ninja>cmake --build .
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.9.0+57a23d249
Copyright (C) Microsoft Corporation.All rights reserved.

  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  build_log.cc
  build.cc
  clean.cc
  clparser.cc
  dyndep.cc
  dyndep_parser.cc
  debug_flags.cc
  deps_log.cc
  disk_interface.cc
  edit_distance.cc
  eval_env.cc
  graph.cc
  graphviz.cc
  line_printer.cc
  manifest_parser.cc
  metrics.cc
  missing_deps.cc
  parser.cc
  state.cc
  status.cc
  コードを生成中...
  コンパイル中...
  string_piece_util.cc
  util.cc
  version.cc
  subprocess-win32.cc
  includes_normalize-win32.cc
  msvc_helper-win32.cc
  msvc_helper_main-win32.cc
  minidump-win32.cc
  コードを生成中...
  getopt.c
  libninja.vcxproj -> C:\build\ninja\libninja.dir\Debug\libninja.lib
  libninja-re2c.vcxproj -> C:\build\ninja\libninja-re2c.dir\Debug\libninja-re2c.lib
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  build_log_perftest.cc
  build_log_perftest.vcxproj -> C:\build\ninja\Debug\build_log_perftest.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  canon_perftest.cc
  canon_perftest.vcxproj -> C:\build\ninja\Debug\canon_perftest.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  clparser_perftest.cc
  clparser_perftest.vcxproj -> C:\build\ninja\Debug\clparser_perftest.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  depfile_parser_perftest.cc
  depfile_parser_perftest.vcxproj -> C:\build\ninja\Debug\depfile_parser_perftest.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  hash_collision_bench.cc
  hash_collision_bench.vcxproj -> C:\build\ninja\Debug\hash_collision_bench.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  manifest_parser_perftest.cc
  manifest_parser_perftest.vcxproj -> C:\build\ninja\Debug\manifest_parser_perftest.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  ninja.cc
  ninja.vcxproj -> C:\build\ninja\Debug\ninja.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
  build_log_test.cc
  build_test.cc
  clean_test.cc
  clparser_test.cc
  depfile_parser_test.cc
  deps_log_test.cc
  disk_interface_test.cc
  dyndep_parser_test.cc
  edit_distance_test.cc
  graph_test.cc
  lexer_test.cc
  manifest_parser_test.cc
  missing_deps_test.cc
  ninja_test.cc
  state_test.cc
  string_piece_util_test.cc
  subprocess_test.cc
  test.cc
  util_test.cc
  includes_normalize_test.cc
  コードを生成中...
  コンパイル中...
  msvc_helper_test.cc
  コードを生成中...
  ninja_test.vcxproj -> C:\build\ninja\Debug\ninja_test.exe
  Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt

c:\build\ninja>
```

**Comment by HideakiAtsuyo** [comment] 2021-03-27 21:19
> First, removing `re2c` from build works for you? Delete(move) `re2c.exe`, clean up repository (`git clean`) and regenerate solution file with CMake then check `RE2C:FILEPATH` set as `RE2C:FILEPATH=RE2C-NOTFOUND` then build it.
> 
> In case it doesn't work, your checkout, CMake or Visual Studio do not work properly for you and I think it isn't Ninja issue. I have confirmed current HEAD ( https://github.com/ninja-build/ninja/tree/8cd25aa78c2ff2ca8b3712f8c3630d1a095856d9 ) can be compiled successfully with following combinations:
> 
> * Windows 10 20H2 English and Japanese
> * CMake `3.19.20122902-MSVC_2` (comes with Visual Studio)
> * Visual Studio 2019 v16.9.2
> * x64
> * NInja generator and MSBuild generator
> * Build in GUI and Visual Studio Command prompt
> * (with or without `re2c`)
> 
> I recommend CMake generation done in Visual Studio Command prompt(x64 Native Tools Command Prompt)
> 
> ![image](https://user-images.githubusercontent.com/100813/112709218-b4ba2b80-8efa-11eb-9b4b-58bc80d4c075.png)
> 
> In case it does not work still, I have no idea what's next... please paste **entire** generation and build log. (You can copy console output with selecting text and hit "Enter"). Since IDE do not provide full logs, build needs to be done with `cmake --build .`
> 
> ```
> **********************************************************************
> ** Visual Studio 2019 Developer Command Prompt v16.9.2
> ** Copyright (c) 2021 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> 
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>cd c:\build\ninja
> 
> c:\build\ninja>cmake c:\cygwin64\home\oku\repos\ninja
> -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
> -- IPO / LTO enabled
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/build/ninja
> 
> c:\build\ninja>cmake --build .
> .NET Framework 向け Microsoft (R) Build Engine バージョン 16.9.0+57a23d249
> Copyright (C) Microsoft Corporation.All rights reserved.
> 
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   build_log.cc
>   build.cc
>   clean.cc
>   clparser.cc
>   dyndep.cc
>   dyndep_parser.cc
>   debug_flags.cc
>   deps_log.cc
>   disk_interface.cc
>   edit_distance.cc
>   eval_env.cc
>   graph.cc
>   graphviz.cc
>   line_printer.cc
>   manifest_parser.cc
>   metrics.cc
>   missing_deps.cc
>   parser.cc
>   state.cc
>   status.cc
>   コードを生成中...
>   コンパイル中...
>   string_piece_util.cc
>   util.cc
>   version.cc
>   subprocess-win32.cc
>   includes_normalize-win32.cc
>   msvc_helper-win32.cc
>   msvc_helper_main-win32.cc
>   minidump-win32.cc
>   コードを生成中...
>   getopt.c
>   libninja.vcxproj -> C:\build\ninja\libninja.dir\Debug\libninja.lib
>   libninja-re2c.vcxproj -> C:\build\ninja\libninja-re2c.dir\Debug\libninja-re2c.lib
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   build_log_perftest.cc
>   build_log_perftest.vcxproj -> C:\build\ninja\Debug\build_log_perftest.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   canon_perftest.cc
>   canon_perftest.vcxproj -> C:\build\ninja\Debug\canon_perftest.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   clparser_perftest.cc
>   clparser_perftest.vcxproj -> C:\build\ninja\Debug\clparser_perftest.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   depfile_parser_perftest.cc
>   depfile_parser_perftest.vcxproj -> C:\build\ninja\Debug\depfile_parser_perftest.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   hash_collision_bench.cc
>   hash_collision_bench.vcxproj -> C:\build\ninja\Debug\hash_collision_bench.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   manifest_parser_perftest.cc
>   manifest_parser_perftest.vcxproj -> C:\build\ninja\Debug\manifest_parser_perftest.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   ninja.cc
>   ninja.vcxproj -> C:\build\ninja\Debug\ninja.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
>   build_log_test.cc
>   build_test.cc
>   clean_test.cc
>   clparser_test.cc
>   depfile_parser_test.cc
>   deps_log_test.cc
>   disk_interface_test.cc
>   dyndep_parser_test.cc
>   edit_distance_test.cc
>   graph_test.cc
>   lexer_test.cc
>   manifest_parser_test.cc
>   missing_deps_test.cc
>   ninja_test.cc
>   state_test.cc
>   string_piece_util_test.cc
>   subprocess_test.cc
>   test.cc
>   util_test.cc
>   includes_normalize_test.cc
>   コードを生成中...
>   コンパイル中...
>   msvc_helper_test.cc
>   コードを生成中...
>   ninja_test.vcxproj -> C:\build\ninja\Debug\ninja_test.exe
>   Building Custom Rule C:/cygwin64/home/oku/repos/ninja/CMakeLists.txt
> 
> c:\build\ninja>
> ```

When i just remove the thing that use re2c, sln, i always have the depfile_parser issue in the screenshot of the other comment.


Everything:

- `git clone --recurse https://github.com/ninja-build/ninja .` Because i was already in Ninja folder
- Created "build" directory
- `cmake ..`
- `cmake --build .` 
=>

```
$ cmake --build .
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  build_log.cc
  build.cc
  clean.cc
  clparser.cc
  dyndep.cc
  dyndep_parser.cc
  debug_flags.cc
  deps_log.cc
  disk_interface.cc
  edit_distance.cc
  eval_env.cc
  graph.cc
  graphviz.cc
  line_printer.cc
  manifest_parser.cc
  metrics.cc
  missing_deps.cc
  parser.cc
  state.cc
  status.cc
  Génération de code en cours...
  Compilation en cours...
  string_piece_util.cc
  util.cc
  version.cc
  subprocess-win32.cc
  includes_normalize-win32.cc
  msvc_helper-win32.cc
  msvc_helper_main-win32.cc
  minidump-win32.cc
  Génération de code en cours...
  getopt.c
  libninja.vcxproj -> C:\Dev\Ninja\build\libninja.dir\Debug\libninja.lib
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  depfile_parser.cc
  lexer.cc
  Génération de code en cours...
  libninja-re2c.vcxproj -> C:\Dev\Ninja\build\libninja-re2c.dir\Debug\libninja-
  re2c.lib
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  build_log_perftest.cc
  build_log_perftest.vcxproj -> C:\Dev\Ninja\build\Debug\build_log_perftest.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  canon_perftest.cc
  canon_perftest.vcxproj -> C:\Dev\Ninja\build\Debug\canon_perftest.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  clparser_perftest.cc
  clparser_perftest.vcxproj -> C:\Dev\Ninja\build\Debug\clparser_perftest.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  depfile_parser_perftest.cc
  depfile_parser_perftest.vcxproj -> C:\Dev\Ninja\build\Debug\depfile_parser_pe
  rftest.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  hash_collision_bench.cc
  hash_collision_bench.vcxproj -> C:\Dev\Ninja\build\Debug\hash_collision_bench
  .exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  manifest_parser_perftest.cc
  manifest_parser_perftest.vcxproj -> C:\Dev\Ninja\build\Debug\manifest_parser_
  perftest.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  ninja.cc
  ninja.vcxproj -> C:\Dev\Ninja\build\Debug\ninja.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
  build_log_test.cc
  build_test.cc
  clean_test.cc
  clparser_test.cc
  depfile_parser_test.cc
  deps_log_test.cc
  disk_interface_test.cc
  dyndep_parser_test.cc
  edit_distance_test.cc
  graph_test.cc
  lexer_test.cc
  manifest_parser_test.cc
  missing_deps_test.cc
  ninja_test.cc
  state_test.cc
  string_piece_util_test.cc
  subprocess_test.cc
  test.cc
  util_test.cc
  includes_normalize_test.cc
  Génération de code en cours...
  Compilation en cours...
  msvc_helper_test.cc
  Génération de code en cours...

  ninja_test.vcxproj -> C:\Dev\Ninja\build\Debug\ninja_test.exe
  Building Custom Rule C:/Dev/Ninja/CMakeLists.txt
```
It's a success ! But... How am i supposed to get the `build.ninja` file, just with the configure in python(i will edit in like 10 mins because i will try)?

**Comment by okuoku** [comment] 2021-03-28 04:09
> How am i supposed to get the build.ninja file,

Hmm, I cannot reproduce your issue on my side.. Since Visual Studio C++ compiler (`cl`) do not work correctly, I'd guess you have something wrong with your x64 Native Tools Command Prompt. For example, In your screenshot, x64 Native Tools Command Prompt seems elevated to Administrator. In normal circumstances, it should not be required.

Please note that even if you're using `bootstrap.py` instead of CMake, whole process needs to be done in Visual Studio Command Prompt because Visual Studio C++ compiler requires some environment variables set up correctly.

`cl` will find include files from `INCLUDE` environment variable. x64 Native Tools Command Prompt should always set up it for you.

```
C:\cygwin64\home\oku\repos\ninja>set INCLUDE
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
```

In my environment, the file `cstdio` was at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include` .

**Comment by HideakiAtsuyo** [comment] 2021-03-28 18:04
> > How am i supposed to get the build.ninja file,
> 
> Hmm, I cannot reproduce your issue on my side.. Since Visual Studio C++ compiler (`cl`) do not work correctly, I'd guess you have something wrong with your x64 Native Tools Command Prompt. For example, In your screenshot, x64 Native Tools Command Prompt seems elevated to Administrator. In normal circumstances, it should not be required.
> 
> Please note that even if you're using `bootstrap.py` instead of CMake, whole process needs to be done in Visual Studio Command Prompt because Visual Studio C++ compiler requires some environment variables set up correctly.
> 
> `cl` will find include files from `INCLUDE` environment variable. x64 Native Tools Command Prompt should always set up it for you.
> 
> ```
> C:\cygwin64\home\oku\repos\ninja>set INCLUDE
> INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
> ```
> 
> In my environment, the file `cstdio` was at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include` .


`py -3.9 configure.py --bootstrap`
=>
Here: https://pastebin.ubuntu.com/p/z3YpSmsmJ9
Because: https://i.imgur.com/jYdNXIM.png 

Looks ok(i used the vs command prompt), it's ok you think? I mean now what i have to do?

**Comment by HideakiAtsuyo** [comment] 2021-03-28 18:11
OK I FIGURED IT OUT, need a build.ninja(made for the project to build) to be able to use it, it's working with vcpkg now, thanks all, tell me when i can close the issue or close it if you can :)

**Comment by okuoku** [comment] 2021-03-29 01:34
Glad to see you finally reached solution. Since only you or project admin can close issue so please close this issue.

**Closed** 2021-03-29 19:11 UTC
Labels: help wanted, windows
