### ISSUE TITLE
1.8-style rebuild-on-failure shouldn't apply to generator tasks

### ISSUE THREAD

**Issue by RedBeard0531** [ninja-build/ninja#1453] opened 2018-07-30 14:16 UTC
While I think it is a good idea in general to remember when tasks fail and consider them not up-to-date, it doesn't seem to work well for generator tasks in particular. The issue is that unlike other tasks, they are often run outside of ninja. This leads to the following unfortunate situation:

1. After an update, a user gets an error regenerating their build.ninja file.
2. The user reruns the generator script with some flags changed, producing a shiny new build.ninja.
3. Ninja reruns the generator script again since it marked it as failed in step 1.

In addition to wasting time, it confuses our users since it seems like the dependencies for the build.ninja file are incorrect.

This feels like a reasonable additional special semantic for `generator=1` rules.

**Comment by jhasse** [comment] 2018-10-29 10:39
Shouldn't the generator in step 2 delete the `.ninja_deps` and `.ninja_log` files when it's run outside of Ninja?

**Comment by mathstuf** [comment] 2018-10-29 13:57
Deleting `.ninja_deps` removes amortized ddep information. Deleting `.ninja_log` removes Ninja's command line change detection database.

**Comment by jhasse** [comment] 2019-02-26 14:18
What about removing all entries for `build.ninja` from `.ninja_log`?

**Comment by mathstuf** [comment] 2019-02-27 21:35
That would work for fixing the issue as state. However, maybe keeping it in the log and detecting if the log time is stale against the disk mtime (similar to #1527) and ignoring the exit code in the log in that case would work better? I'd still like Ninja to rerun the failed generator step if I *haven't* manually rerun the generator.

**Comment by jhasse** [comment] 2019-02-27 22:49
> However, maybe keeping it in the log and detecting if the log time is stale against the disk mtime (similar to #1527) and ignoring the exit code in the log in that case would work better? 

Hm ... why would that be better?

**Comment by mathstuf** [comment] 2019-02-28 01:22
There are a few cases here:

  - if the build log says "failed, please rerun" and the mtime on disk is *newer*, trust the user did the right thing and continue as-is (e.g., `$EDITIOR ../src/CMakeLists.txt && cmake . && ninja`).
  - if the build log says "failed, please rerun" and the mtime on disk has not changed, rerun the rule (e.g., `$EDITOR ../src/CMakeLists.txt && ninja`).

Removing the generator rule from the build log completely means the second might not work. Or maybe that would still work anyways?

**Comment by jhasse** [comment] 2019-02-28 09:50
What I meant was, that *CMake* could remove the `build.ninja` lines from the log when it runs (successfully).

**Comment by mathstuf** [comment] 2019-02-28 12:15
That means that if the format changes, CMake needs a new release to use newer ninja binaries. I don't think that is wise in the long run.

**Comment by jhasse** [comment] 2019-02-28 12:20
I don't think the format will change in the foreseeable future, so that's not a big problem.

In your first example, there would be a bug, if running `cmake .` was unsuccessful (but still touched `build.ninja`).

**Comment by mathstuf** [comment] 2019-02-28 12:45
I wonder if we could consider that a CMake bug at that point. IIRC, the `build.ninja` isn't touched until generation is successful. A quick look at the code confirms this; I wonder if we have tests to that effect though. @bradking can anything go wrong between the check for errors and setting the failbit and closing the `cmGeneratedFileStream`? Other than `ENOSPC` or `EPERM` which should also probably cause noise from `ninja` anyways.

**Comment by mathstuf** [comment] 2019-03-01 12:51
> I don't think the format will change in the foreseeable future, so that's not a big problem.

For the record, the discussion about the Android build speed thread has mentioned that this might be something to look at for "more efficient loading".

**Comment by jhasse** [comment] 2019-03-01 13:15
Yes, I immediately thought about this issue, too. Maybe ninja could provide a tool instead, which handles the removal from the log.

**Comment by jhasse** [comment] 2019-05-10 14:49
Closing as duplicate of #1376 (correct me if I'm wrong).

**Closed by jhasse** 2019-05-10 14:49 UTC
