### ISSUE TITLE
how to block tons of "Note: including file: "

### ISSUE THREAD

**Issue by betterpig** [ninja-build/ninja#2039] opened 2021-11-01 13:14 UTC
hi, I am using ninja as my C++ project generator when compile by cmake. However, there are tons of "Note: including file: ....h" when compiling, just like picture below. I get to know that it's because ninja add /showIncludes flag in cl command  to get C/C++ header dependencies. But it seems not useful for develper to find out the actual compiling problem. 
![image](https://user-images.githubusercontent.com/51314274/139676336-3458a705-1d2d-4400-8142-926e99a0d289.png)

I tried to delete all \showIncludes, deps = msvc in rules.ninja and build again, but it didn't help. I also tried to delete CMAKE_CXX_CL_SHOWINCLUDES_PREFIX in CMakeCXXCompiler.cmake, didn't help too. 

So I wonder if there is a way to set some option to not show them. Look forward to your reply.

Best wishes!

**Comment by jhasse** [comment] 2021-11-08 08:47
duplicate of #613

**Closed by jhasse** 2021-11-08 08:47 UTC
