### ISSUE TITLE
Use sub-1s resolution in timestamps

### ISSUE THREAD

**Issue by evmar** [ninja-build/ninja#371] opened 2012-07-27 18:35 UTC
There's a pull request here that implements it:
https://github.com/martine/ninja/pull/337

However, the timing changes are mixed in with other unrelated changes, so finishing this bug will involve extracting that logic.

**Comment by nirbheek** [comment] 2016-10-12 14:45
We're hitting this in [Meson](/mesonbuild/meson) when timestamps are within 200ms of each other. What's blocking Ninja from moving to millisecond-resolution granularity in timestamp checking? How can we help with this?

**Comment by mathstuf** [comment] 2016-10-12 15:06
I think the issue is that no one has extracted the relevant bits from #337 into its own PR.

**Comment by nirbheek** [comment] 2016-10-12 15:14
Okay, thanks, I'll work on that then. :)

**Comment by QuLogic** [comment] 2017-05-10 00:02
Ping? This is making Meson testing painfully slow as it needs to wait 1 second on every test just to be sure ninja will work. And there's a PR available...

**Closed** 2017-10-20 17:18 UTC
Labels: feature
