### ISSUE TITLE
Ninja unnecessarily runs CMake just after it was run manually

### ISSUE THREAD

**Issue by Ede123** [ninja-build/ninja#1376] opened 2018-01-28 15:45 UTC
Cross-posting [an issue from CMake bugtracker](https://gitlab.kitware.com/cmake/cmake/issues/17531) as I suspect this might be a ninja issue.

Just after running CMake manually, ninja decides to re-run CMake:
```
ninja explain: recorded mtime of build.ninja older than most recent input CMakeCache.txt (538856124 vs 538856322)
```
while the file is newer on disk

```
$ stat -c %Y build.ninja CMakeCache.txt
1517153123
1517153122
```

**Comment by Ede123** [comment] 2018-01-28 15:46
@QuLogic could this have been caused by 5fcdcf95cb62ab3d593c36ef90df27cef63874a1?

**Comment by topilski** [comment] 2018-02-24 06:12
Any updates?

**Comment by nico** [comment] 2018-04-05 15:18
Is this a regression? Does it happen with the current stable ninja? If so, it's not due to high-res timestamps, those aren't in a release yet.

Might be a dupe of #906.

**Comment by topilski** [comment] 2018-04-05 15:19
Hi @nico, i used 1.8.2 version.

**Comment by tchernobog** [comment] 2018-05-23 07:00
I was also heavily affected by this bug (a CMake run for us runs in about one minute and a half on Linux, about 6 minutes on Windows), so I tried compiling ninja from the master branch.

It appears I cannot reproduce this bug anymore. @Ede123 could you please try ninja master and see if the issue still persists for you?

**Comment by ojura** [comment] 2018-08-11 09:04
I have reproduced it. Ninja uses the timespamp in`.ninja_log`, it seems, and that one can fall out of date.

**Comment by rnk** [comment] 2018-09-05 20:54
I don't think this is #906, because my build.ninja is newer than my CMakeCache.txt:
```
$ stat build.ninja CMakeCache.txt
  File: build.ninja
...
Modify: 2018-09-05 13:38:28.056863700 -0700
  File: CMakeCache.txt
...
Modify: 2018-09-05 13:27:03.224376800 -0700
```
But if I compile some random target, ninja says the "recorded mtime" of build.ninja is older:
```
$ ninja -n -d explain not
ninja explain: recorded mtime of build.ninja older than most recent input LLVMBuild.cmake (557882386 vs 557883085)
[1 processes, 0/1 @ ?/s : 0.000s ] Re-running CMake...
```
As a workaround, if I run this sed command after manually running cmake, I get the behavior I want:
```
$ sed  '/\tbuild\.ninja\t/d' .ninja_log -i
```

**Comment by maikelvdh** [comment] 2018-10-31 23:18
Noticing exactly the same issue with 1.8.2 and also with latest master! Moving back to 1.7.2 this seems to be no problem as the build.ninja entry in .ninja_log seems to be ignored in this release.

**Comment by jhasse** [comment] 2018-11-02 09:14
Is this #1453?

**Comment by maikelvdh** [comment] 2018-11-08 07:12
That bug seems kind of related, yes!

**Comment by fkaelberer** [comment] 2019-01-21 10:11
Any progress on this bug? It would really make my day if this would land in 1.9.

**Comment by dzenanz** [comment] 2019-05-06 17:28
This is present in 1.9.0. Any news since?

**Comment by donhinton** [comment] 2019-05-24 18:14
This worked for me:

diff --git a/src/ninja.cc b/src/ninja.cc
index a093cd1..810b22d 100644
--- a/src/ninja.cc
+++ b/src/ninja.cc
@@ -249,8 +249,6 @@ bool NinjaMain::RebuildManifest(const char* input_file, string* err) {
     return false;

   Builder builder(&state_, config_, &build_log_, &deps_log_, &disk_interface_);
-  if (!builder.AddTarget(node, err))
-    return false;

   if (builder.AlreadyUpToDate())
     return false;  // Not an error, but we didn't rebuild.

**Comment by donhinton** [comment] 2019-05-24 20:44
While my previous diff fixed the problem, it also prevented reconfig based on config file updates.  Here's a better solution.  All it does is prevent adding "build.ninja" to .ninja_log.

```
diff --git a/src/build_log.cc b/src/build_log.cc
index c4a08a0..ba77b33 100644
--- a/src/build_log.cc
+++ b/src/build_log.cc
@@ -168,6 +168,8 @@ bool BuildLog::RecordCommand(Edge* edge, int start_time, int end_time,
       log_entry = new LogEntry(path);
       entries_.insert(Entries::value_type(log_entry->output, log_entry));
     }
+    if (path == "build.ninja")
+      continue;
     log_entry->command_hash = command_hash;
     log_entry->start_time = start_time;
     log_entry->end_time = end_time;
```

**Comment by bobzhang** [comment] 2019-07-02 03:36
hit the same issue in master branch:
```
jscomp>ls -al -T  stubs/ext_basic_hash_stubs.o stubs/libbs_hash.a 
-rw-r--r--  1 hongbozhang  staff  2388 Jul  2 11:27:05 2019 stubs/ext_basic_hash_stubs.o
-rw-r--r--  1 hongbozhang  staff  2856 Jul  2 11:27:44 2019 stubs/libbs_hash.a
jscomp>ninja -n stubs/stubs.cmxa --verbose -d explain
ninja explain: recorded mtime of stubs/libbs_hash.a older than most recent input stubs/ext_basic_hash_stubs.o (156203765467865\
5824 vs 1562038025157065405)
ninja explain: stubs/libbs_hash.a is dirty
[1/2] ../native/4.06.1/bin/ocamlmklib stubs/ext_basic_hash_stubs.o -o stubs/bs_hash
[2/2] ../native/4.06.1/bin/ocamlopt.opt -a stubs/bs_hash_stubs.cmx -o stubs/stubs.cmxa -cclib stubs/libbs_hash.a
```

**Closed** 2020-01-04 13:21 UTC
Labels: bug

**Comment by Ede123** [comment] 2020-01-04 14:58
@jhasse Nice to see some progress on this!

If I understand correctly #1685 did *not* fix this issue yet, but only added the required tooling that could be used to address the issue? If so could you re-open it please?

The tooling will then be used (and then fix this issue), once https://gitlab.kitware.com/cmake/cmake/merge_requests/3316 is merged, correct?

**Comment by jhasse** [comment] 2020-01-04 15:07
Yes, but keeping this open would make it sound like a Ninja issue, but in reality it's kind of a CMake+Ninja issue. IMHO bugs related to CMake's Ninja generator should be tracked in CMake's bug tracker instead (with the `gen:ninja` label). So I think the right place to track this issue is https://gitlab.kitware.com/cmake/cmake/issues/15830.

**Comment by Ede123** [comment] 2020-01-04 15:09
OK, thanks, as long as it's not forgotten I'm fine with having this tracked over at the CMake tracker exclusively.

**Comment by ilor** [comment] 2020-01-06 10:13
I'm seeing a very similar issue in the GN build, where running gn would then make ninja cause another GN run.
> $ stat -c "%Y %n build.ninja args.gn
> 1578304921 build.ninja
> 1578304914 args.gn

Ninja -d explain says
> ninja explain: recorded mtime of build.ninja older than most recent input args.gn (1578304024652337947 vs 1578304914278584518)

I was assuming it's the same issue cmake had, but now I'm not sure.. What I'm getting if I issue a ninja -t restart after the initial gn run is that while gn is not re-run, all outputs become invalid. As I'm seeing this issue in incremental nearly-done builds too, that's far from ideal. Any hints?

**Comment by jhasse** [comment] 2020-01-06 15:01
> What I'm getting if I issue a ninja -t restart after the initial gn run is that while gn is not re-run, all outputs become invalid. As I'm seeing this issue in incremental nearly-done builds too, that's far from ideal.

That would be a bug. Can you try to create a minimal reproducible example and create a new issue?

(it's `ninja -t restat` btw)

**Comment by ilor** [comment] 2020-01-08 20:13
OK, filed #1718 with what I have for now, I'll try to look for a smaller / more reliable repro when I have the time. 

(For the record, "restart" was a typo in the comment here, I did use `restat`)
