### ISSUE TITLE
ninja-1.11.0 does not honor "ninja -j 1 test" - "-j 1"

### ISSUE THREAD

**Issue by ijaaskelainen** [ninja-build/ninja#2163] opened 2022-07-05 05:52 UTC
System specs are: meson-0.63.0 and ninja-1.11.0 both from pip / pypi. The ninja still runs multiple processes..

**Comment by jhasse** [comment] 2022-07-06 13:01
We need more info to reproduce.

**Comment by ijaaskelainen** [comment] 2022-07-07 08:41
I am trying to run pixman-0.40.0 test suite with meson + ninja. You think the cause is up there?

Neither did I find a parameter for
"meson test"
to limit the amount of build processes being spawn.

My pixman-0.40.0 test TIMEOUT issues got resolved by running
"meson test --timeout-multiplier=5"
instead of
"ninja -j 1 test"
but as an interesting side-effect still seems to ignore the build process limit set by user.

Thus is no longer blocking my build.

**Comment by YusufKhan-gamedev** [comment] 2022-07-15 01:22
Same issue, major issue for my phone on ubports since it keeps freezing when too many processes are running.

**Comment by jonesmz** [comment] 2022-08-25 23:15
So is the problem that `ninja -j 1` isn't working?

Can you provide a minimal reproduction? E.g. a ninjafile that's only got a few commands, where we can download the ninja file and observe that the `-j 1` CLI arg isn't limiting the number of parallel processes?

**Comment by eli-schwartz** [comment] 2022-08-26 00:47
`ninja -j 1 test` is a build rule to run a "test" target that spawns a testsuite.

There are no build processes to spawn unless they happen to be run first as a dependency. Re-running `ninja test` will repeatedly run the testsuite, but all programs will have been built by the second run, so...

... I have a nagging suspicion that the process parallelism you are talking about isn't ninja compilations at all? It is, rather, the number of tests being tested in parallel (the entire test harness is a single ninja job).

There's a meson option for this: `meson test --num-processes=1`.
You can also set `$MESON_TESTTHREADS` to 1.

**Comment by jonesmz** [comment] 2022-08-26 01:16
I agree with @eli-schwartz  this *appears* to be a situation where `ninja` is only launching one process (at a time, or at all), but the sub-process is a test-runner which may have it's own set of sub-processes that it launches.

If you're able to provide a minimal reproduction that demonstrates `ninja -j1` running (*directly*) more than one subprocess at a time, that would be a bug in `ninja`.

But without more info, this seems instead like a bug in meson or your test system.

**Comment by eli-schwartz** [comment] 2022-08-26 01:56
It's not a bug in anything, it's just a misunderstanding.

Okay, well, actually it is a bug in ninja. A design bug, and a maintainer personality bug. ;)

When will we get `$NINJAFLAGS`? Hmm? Something something the time spent to perform `getenv(2)` constitutes a dealbreaking performance regression, therefore ninja will never parse environment variables no matter how useful?

**Comment by jonesmz** [comment] 2022-08-26 06:05
I wasn't aware there was any perf problem with getenv(). Wouldn't that only be called once per invocation of the ninja process, at the beginning? Its surprising to me that was an issue?

**Comment by eli-schwartz** [comment] 2022-08-26 06:25
> I wasn't aware there was any perf problem with getenv().

Of course there is not an actual perf problem.

> Wouldn't that only be called once per invocation of the ninja process, at the beginning?

Right.

> Its surprising to me that was an issue?

It's pretty obvious that that wasn't the real issue, it's just the one that was officially claimed.

In one of the 14+ issues/PRs about adding a NINJAFLAGS environment variable. I think it's probably *the* most popular, recurring pain point that ninja users have. It would be a perfect solution to this case. And the ninja maintainers will spend *years* on end arguing that they're not interested in such a feature, it's slow, "ninja documents that it only uses one environment variable", etc. etc. etc.

Fortunately, samurai immediately accepted a PR to implement $SAMUFLAGS. But it's of limited use in scripts when most people use ninja.

**Comment by jonesmz** [comment] 2022-08-26 06:37
Ah. Thanks for explaining. Yea, I have my grips on how many pull requests I've had closed. *shrug*. I use ninja professionally, and am expected to be able to patch it for my issues at work. Pretty frustrating to not be able to get most of my patches merged for years.

**Comment by jhasse** [comment] 2022-09-05 10:53
> ... I have a nagging suspicion that the process parallelism you are talking about isn't ninja compilations at all? It is, rather, the number of tests being tested in parallel (the entire test harness is a single ninja job).

**Closed by jhasse** 2022-09-05 10:53 UTC
