### ISSUE TITLE
-t deps command has weird parsing behavior, causes odd quirks

### ISSUE THREAD

**Issue by randomascii** [ninja-build/ninja#1369] opened 2017-12-28 02:02 UTC
I am making use of ninja's "-t deps" command and I have found that it is quirky in its handling of command-line arguments. This works:

    ninja -C out\debug_component_64 -t deps >deps.txt

However this fails cryptically:

    ninja -d stats -C out\debug_component_64 -t deps >foo.txt
    ninja: error: unknown target '-d', did you mean '2d'?

I routinely auto-append -d stats so I hit this frequently. This doesn't happen with other -d commands such as -d keeprsp.

This also fails:

    ninja -t deps -C out\debug_component_64 > deps2.txt
    ninja: error: loading 'build.ninja': The system cannot find the file specified.

It looks like the -t deps command is issued immediately without waiting for the -C command to take effect.

**Comment by nico** [comment] 2018-04-05 01:05
The way ninja parses its args is left to right. Things in front of -t are handled by "main ninja", things after -t are handled by the tool logic. This explains the latter error. I can't reproduce the former one:
```
ninja -d stats -C out/gn -t deps > /dev/null
```

**Comment by randomascii** [comment] 2018-04-05 17:48
The first error is self inflicted, caused by a ninja wrapper I use that adds -d keeprsp so that the final command is:

> ninja.exe -d stats -C out\debug_component -t deps  -d keeprsp

So the first "bug" is that multiple -d options are not handled correctly. The appending of -d keeprsp was done both to simplify compiler repros and to improve build performance (back when we created .rsp files for every compile step).

For -t I can now see that the help mentions this (it says "terminates toplevel options; further flags are passed to the tool"). Maybe it should say that -t must be last, or maybe it's fine as-is.

**Comment by nico** [comment] 2018-04-05 17:55
It sounds like the -t parsing explains the issues seen, and the behavior is even kind-of documented :-) Let's close this out.

**Closed by nico** 2018-04-05 17:55 UTC
