### ISSUE TITLE
Enhancement: support --color=never, --color=auto, --color=always

### ISSUE THREAD

**Issue by gerion0** [ninja-build/ninja#1503] opened 2018-11-20 15:59 UTC
With current ninja colored output exists only in the "smart" way. ninja deactivates the colors, when piped into something:
```
$ ninja       # colored output
$ ninja | cat # not colored output
```
A lot of programs (like ls and grep) have a command line flag to change this behaviour. It would be nice, if ninja supports this, too:
```
$ ninja --color=always       # colored output
$ ninja --color=always | cat # colored output
$ ninja --color=never        # not colored output
$ ninja --color=never | cat  # not colored output

**Comment by jhasse** [comment] 2018-11-20 16:01
Duplicate of #1475.

**Closed by jhasse** 2018-11-20 16:01 UTC
