### ISSUE TITLE
URL in the doc is wrong

### ISSUE THREAD

**Issue by zoobab** [ninja-build/ninja#1397] opened 2018-03-15 10:49 UTC
In:

https://ninja-build.org/manual.html

There is a link to:

https://chromium.googlesource.com/chromium/src/+/master/docs/ninja_build.md

Which gives a 404.

**Comment by zoobab** [comment] 2018-03-15 10:50
This is in the section:

Ninja’s benefit comes from using it in conjunction with a smarter meta-build system.

gyp
    The meta-build system used to generate build files for Google Chrome and related projects (v8, node.js). gyp can generate Ninja files for all platforms supported by Chrome. See the Chromium Ninja documentation for more details.

**Comment by jhasse** [comment] 2018-11-07 15:19
Duplicate of #1263.

**Closed by jhasse** 2018-11-07 15:19 UTC
