### ISSUE TITLE
Error bootstrapping Ninja: insecure string pickle

### ISSUE THREAD

**Issue by yesmar** [ninja-build/ninja#1216] opened 2016-12-21 01:05 UTC
An unhandled exception is preventing me from bootstrapping Ninja from source. I get the following stack trace when I run `CXX=clang++ ./configure.py --bootstrap` on macOS 10.12.2 Sierra:

```python
bootstrapping ninja...
Traceback (most recent call last):
  File "./configure.py", line 462, in <module>
    if has_re2c():
  File "./configure.py", line 458, in has_re2c
    proc = subprocess.Popen(['re2c', '-V'], stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

I did make an effort to see if this issue had been reported before, but I didn't see anything.

I'm not a Python person, so I'm using the stock Python on macOS Sierra, which reports itself as being version 12.7.10. I did a little research on `insecure string pickle` and discovered that this is a [known issue](http://bugs.python.org/issue26083) involving the `subprocess` module. Apparently, this issue is fixed in Python 2.7.12, which has not been incorporated into macOS yet. As a result, I can't build Ninja from source as is. The brute force fix would be installing another Python, but that is something I would rather avoid, if possible.

**Comment by nico** [comment] 2016-12-21 04:46
I too am on macOS Sierra 12.12.2 and things work fine for me. What's `which python`? Do you use brew or something like that?

**Comment by yesmar** [comment] 2016-12-21 04:48
I don’t use Homebrew or anything like that.

**Comment by evmar** [comment] 2016-12-21 22:06
This appear to be some weird Python bug for when the program is missing... or something?
https://bugs.python.org/issue26083

**Comment by yesmar** [comment] 2016-12-21 22:10
That sounds about right, @evmar. I don't have `re2c` installed, so the `ValueError` exception is happening. Not catching it results in `configure.py` crashing. My patch catches it and, like the `OSError` case, returns `False`. This lets `configure.py` continue running. No code changes in `src/` will be processed, but for someone who just wants to bootstrap Ninja from source (me), this is fine. If you want to develop on Ninja then obviously you will need to install `re2c`.

**Comment by nico** [comment] 2016-12-24 20:18
I don't have re2c in PATH on my system either. I'm at python 2.7.10 too (default system python). I wonder why it works for me but not for you.

I tried _adding_ re2c to PATH but still don't see the bug.

What do you get when you manually run `re2c -V` in the shell that you're running configure in? What's the output of `env`?

**Comment by yesmar** [comment] 2016-12-24 20:25
```bash
$ which re2c
$ re2c -V
-bash: re2c: command not found
$ env
TERM=xterm-256color
SHELL=/bin/bash
USER=ramsey
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/ramsey
SHLVL=1
HOME=/var/empty
_=/usr/bin/env
```

**Comment by QuLogic** [comment] 2016-12-31 00:37
This odd exception can also be fixed by using the `subprocess32` backport instead.

**Comment by jhasse** [comment] 2018-11-02 11:20
(see #1217)

Has macOS 10.13 updated its Python version?

**Comment by jhasse** [comment] 2018-11-16 11:37
You'll need 2.7.12 (or 3).

**Comment by nico** [comment] 2018-11-16 15:04
We should try to work with system python on macOS -- but it works fine over here. If anyone has any suggestions how I could repro this locally, or why you're seeing this and I'm not, I'd be very interested in hearing them.

**Comment by jonesmz** [comment] 2020-02-05 09:28
@jhasse CMake vs. Configure.py

**Comment by jhasse** [comment] 2020-02-05 09:42
Closing because I can't reproduce this on macOS. Also there's now CMake as a fallback.

**Closed by jhasse** 2020-02-05 09:42 UTC
