### ISSUE TITLE
Incorporate Windows exit code in the "FAILED: " and "subcommand failed" error messages.

### ISSUE THREAD

**Issue by camohr** [ninja-build/ninja#2439] opened 2024-05-05 13:09 UTC
Instead of:
- `FAILED: ` _outputs, etc._
- `ninja: build stopped: subcommand failed`

something like:
- `FAILED: exit code -1073741571 (0xC00000FD) ` _outputs, etc._
- `ninja: build stopped: subcommand failed, returned exit code -1073741571 (0xC00000FD).`

This would be especially helpful when the offending command fails without emitting an appropriate (or any) error message. In my case the MSVC CL compiler (v19.39.33523 x64) simply stopped while compiling a very large source file. Replaying the CL invocation at the command prompt didn't reveal anything. Eventually I ran it in a .bat script and observed its exit code via %ERRORLEVEL%.  Technically I had enough info to find my root cause, it just took me longer because of CL's quasi-silent failure. Ninja displaying the exit code definitely would've helped.

**Comment by jhasse** [comment] 2024-05-05 13:52
duplicate of #2439

**Comment by jhasse** [comment] 2024-05-05 13:53
duplicate of #1507

**Closed by jhasse** 2024-05-05 13:53 UTC
Labels: frontend
